# Generated by Django 5.2.10 on 2026-09-27 09:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('web', '0003_seed_leadership_team'),
    ]

    def create_leadership_groups(apps, schema_editor):
        group_model = apps.get_model('auth', 'Group')
        for name in ('President', 'Secretary'):
            group_model.objects.using(schema_editor.connection.alias).get_or_create(name=name)

    operations = [
        migrations.CreateModel(
            name='ClubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('class_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
                ('membership_fee_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('membership_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_present', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='web.member')),
            ],
            options={
                'ordering': ['-date', 'member__name'],
                'constraints': [models.UniqueConstraint(fields=('member', 'date'), name='unique_member_attendance_date')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_fees', to='web.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='web.clubproject')),
            ],
            options={
                'ordering': ['project__name', 'member__name'],
                'constraints': [models.UniqueConstraint(fields=('member', 'project'), name='unique_member_project_fee')],
            },
        ),
        migrations.RunPython(create_leadership_groups, migrations.RunPython.noop),
    ]
