# Generated by Django 5.2.10 on 2026-10-01 11:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def fill_missing_member_classes(apps, schema_editor):
	Member = apps.get_model('web', 'Member')
	Member.objects.filter(class_name='').update(class_name='Senior 1')


def seed_leader_memberships(apps, schema_editor):
	Leader = apps.get_model('web', 'Leader')
	Member = apps.get_model('web', 'Member')
	AuditLog = apps.get_model('web', 'AuditLog')
	for leader in Leader.objects.filter(is_visible=True):
		member, created = Member.objects.get_or_create(
			name=leader.name,
			defaults={
				'class_name': 'Senior 1',
				'membership_fee_due': 0,
				'membership_fee_paid': 0,
				'is_leader': True,
			},
		)
		member.class_name = member.class_name or 'Senior 1'
		member.membership_fee_due = 0
		member.membership_fee_paid = 0
		member.is_leader = True
		member.save(update_fields=[
			'class_name', 'membership_fee_due', 'membership_fee_paid', 'is_leader',
		])
		if created:
			AuditLog.objects.create(
				action='added',
				details=f'Leader profile {leader.name} was automatically added as a club member.',
				model_name='Member',
				object_name=leader.name,
			)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_club_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubproject',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='member',
            name='removed_academic_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='removed_term',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='resource-categories/'),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('removed', 'Removed'), ('attendance', 'Attendance'), ('fee', 'Fee'), ('announcement', 'Announcement'), ('resource', 'Resource'), ('restored', 'Restored'), ('period', 'Period'), ('expense', 'Expense')], max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='class_name',
            field=models.CharField(choices=[('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3'), ('Senior 4', 'Senior 4'), ('Senior 5', 'Senior 5'), ('Senior 6', 'Senior 6')], default='Senior 1', max_length=80),
        ),
        migrations.CreateModel(
            name='ClubPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(default=2026)),
                ('term', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_period_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'club academic period',
            },
        ),
        migrations.CreateModel(
            name='LeaderNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seen_by_leader_states', to='web.auditlog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_notification_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='web.clubproject')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(fill_missing_member_classes, migrations.RunPython.noop),
        migrations.RunPython(seed_leader_memberships, migrations.RunPython.noop),
    ]
