# Generated by Django 5.2.10 on 2026-10-01 11:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_clubproject_image_file_member_removed_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('removed', 'Removed'), ('attendance', 'Attendance'), ('fee', 'Fee'), ('announcement', 'Announcement'), ('resource', 'Resource'), ('restored', 'Restored'), ('period', 'Period'), ('expense', 'Expense'), ('income', 'Income')], max_length=30),
        ),
        migrations.CreateModel(
            name='ClubIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='web.clubproject')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_income_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
