# Generated by Django 5.2.10 on 2026-10-01 12:49

from django.db import migrations, models


def add_opening_fee_income(apps, schema_editor):
	ClubIncome = apps.get_model('web', 'ClubIncome')
	ClubPeriod = apps.get_model('web', 'ClubPeriod')
	Member = apps.get_model('web', 'Member')
	ProjectFee = apps.get_model('web', 'ProjectFee')
	period = ClubPeriod.objects.filter(pk=1).first()
	year = period.academic_year if period else 2026
	term = period.term if period else 1
	membership_total = Member.objects.aggregate(total=models.Sum('membership_fee_paid'))['total']
	if membership_total:
		ClubIncome.objects.create(
			activity='Membership fees',
			description='Opening balance from membership fees recorded before term-based finance tracking.',
			amount=membership_total,
			academic_year=year,
			term=term,
		)
	project_total = ProjectFee.objects.aggregate(total=models.Sum('amount_paid'))['total']
	if project_total:
		ClubIncome.objects.create(
			activity='Project fees',
			description='Opening balance from project fees recorded before term-based finance tracking.',
			amount=project_total,
			academic_year=year,
			term=term,
		)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_seed_patron_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubincome',
            name='academic_year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='clubincome',
            name='term',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='academic_year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='term',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clubincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
		migrations.RunPython(add_opening_fee_income, migrations.RunPython.noop),
    ]
