# Generated by Django 5.2.10 on 2026-10-01 13:09

from django.db import migrations, models


def remove_resource_uploads_and_audit_entries(apps, schema_editor):
    ResourceCategory = apps.get_model('web', 'ResourceCategory')
    ResourceItem = apps.get_model('web', 'ResourceItem')
    AuditLog = apps.get_model('web', 'AuditLog')

    for category in ResourceCategory.objects.exclude(image_file='').iterator():
        category.image_file.storage.delete(category.image_file.name)
    for resource in ResourceItem.objects.exclude(uploaded_file='').iterator():
        resource.uploaded_file.storage.delete(resource.uploaded_file.name)
    AuditLog.objects.filter(action='resource').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_clubincome_academic_year_clubincome_term_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_resource_uploads_and_audit_entries, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='resourceitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resourceitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resourceitem',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('removed', 'Removed'), ('attendance', 'Attendance'), ('fee', 'Fee'), ('announcement', 'Announcement'), ('restored', 'Restored'), ('period', 'Period'), ('expense', 'Expense'), ('income', 'Income')], max_length=30),
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
        migrations.DeleteModel(
            name='ResourceItem',
        ),
    ]
